<?xml version="1.0"?>
<robot>
  <!--Gazebo Differential Drive Plugin-->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <publishWheelTF>false</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <alwaysOn>true</alwaysOn>
      <legacyMode>false</legacyMode>
      <updateRate>40</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>spot_sim/cmd_vel</commandTopic>
      <odometryTopic>spot_sim/odom</odometryTopic>
      <odometryFrame>spot_sim/odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo>
</robot>
